//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantCare.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlantCare.App.Resources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is added.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plants found. Add a new plant to get started!.
        /// </summary>
        internal static string AddMyPlants {
            get {
                return ResourceManager.GetString("AddMyPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        internal static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Calendar.
        /// </summary>
        internal static string CareCalendar {
            get {
                return ResourceManager.GetString("CareCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export/Import.
        /// </summary>
        internal static string DataImportExport {
            get {
                return ResourceManager.GetString("DataImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilization.
        /// </summary>
        internal static string Fertilization {
            get {
                return ResourceManager.GetString("Fertilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilization Interval.
        /// </summary>
        internal static string FertilizationInterval {
            get {
                return ResourceManager.GetString("FertilizationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilization Notification.
        /// </summary>
        internal static string FertilizationNotification {
            get {
                return ResourceManager.GetString("FertilizationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilization Schedule.
        /// </summary>
        internal static string FertilizationSchedule {
            get {
                return ResourceManager.GetString("FertilizationSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Fertilization Time.
        /// </summary>
        internal static string LastFertilization {
            get {
                return ResourceManager.GetString("LastFertilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Watering Time.
        /// </summary>
        internal static string LastWatering {
            get {
                return ResourceManager.GetString("LastWatering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as done and update the last attended time as now.
        /// </summary>
        internal static string MarkDone {
            get {
                return ResourceManager.GetString("MarkDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Fertilization.
        /// </summary>
        internal static string ModifyLastFertilization {
            get {
                return ResourceManager.GetString("ModifyLastFertilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Watering.
        /// </summary>
        internal static string ModifyLastWatering {
            get {
                return ResourceManager.GetString("ModifyLastWatering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Plants.
        /// </summary>
        internal static string MyPlants {
            get {
                return ResourceManager.GetString("MyPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Fertilization.
        /// </summary>
        internal static string NextFertilization {
            get {
                return ResourceManager.GetString("NextFertilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Watering.
        /// </summary>
        internal static string NextWatering {
            get {
                return ResourceManager.GetString("NextWatering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Existing Data.
        /// </summary>
        internal static string RemoveExistingData {
            get {
                return ResourceManager.GetString("RemoveExistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Plants by Name.
        /// </summary>
        internal static string SearchPlantByName {
            get {
                return ResourceManager.GetString("SearchPlantByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set As Now.
        /// </summary>
        internal static string SetAsNow {
            get {
                return ResourceManager.GetString("SetAsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Logs.
        /// </summary>
        internal static string ShowLogs {
            get {
                return ResourceManager.GetString("ShowLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        internal static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Fertilization in .
        /// </summary>
        internal static string TillNextFertilization {
            get {
                return ResourceManager.GetString("TillNextFertilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Watering in.
        /// </summary>
        internal static string TillNextWatering {
            get {
                return ResourceManager.GetString("TillNextWatering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unattended Only.
        /// </summary>
        internal static string UnattendedOnly {
            get {
                return ResourceManager.GetString("UnattendedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is updated.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watering.
        /// </summary>
        internal static string Watering {
            get {
                return ResourceManager.GetString("Watering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watering Interval.
        /// </summary>
        internal static string WateringInterval {
            get {
                return ResourceManager.GetString("WateringInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watering Notification.
        /// </summary>
        internal static string WateringNotification {
            get {
                return ResourceManager.GetString("WateringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watering Schedule.
        /// </summary>
        internal static string WateringSchedule {
            get {
                return ResourceManager.GetString("WateringSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
